name: ประกาศสายตามเสียง

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  ping_discord:
    runs-on: ubuntu-latest
    steps:
      - name: เตรียมข้อความไปด่… เอ๊ย ไปแจ้ง
        id: prep
        run: |
          set -e # ให้สคริปต์หยุดทันทีถ้ามี error

          if [[ "${{ github.event_name }}" == "push" ]]; then
            # กรณี push
            COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')
            MSG="มีการ push ใส่ branch **${{ github.ref_name }}** โดย **${{ github.actor }}**
            **ข้อความ:** ${COMMIT_MSG:-"(ไม่มีข้อความคอมมิต)"}
            **ดูการเปลี่ยนแปลง:** ${{ github.event.compare }}"

          else
            # กรณี pull request
            PR_ACTION="${{ github.event.action }}"
            PR_MERGED="${{ github.event.pull_request.merged }}"
            PR_NUM="${{ github.event.pull_request.number }}"
            PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr '\n' ' ')
            
            STATE="PR #${PR_NUM} (${PR_ACTION})"
            if [[ "$PR_ACTION" == "closed" && "$PR_MERGED" == "true" ]]; then
              STATE="✅ PR #${PR_NUM} ถูกรวม (merged) แล้ว"
            elif [[ "$PR_ACTION" == "closed" ]]; then
              STATE="❌ PR #${PR_NUM} ถูกปิด (closed) โดยไม่รวม"
            fi

            MSG="${STATE}
            **หัวข้อ:** ${PR_TITLE}
            **ลิงก์:** ${{ github.event.pull_request.html_url }}
            **คนก่อเรื่อง:** **${{ github.actor }}**"
          fi

          # ส่งตัวแปร MSG เข้า GITHUB_ENV เพื่อให้ python เรียกใช้ได้
          echo "DISCORD_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$MSG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: สร้าง JSON Payload
        id: json_payload
        run: |
          python -c '
          import json, os
          msg = os.environ.get("DISCORD_MESSAGE", "")
          payload = json.dumps({"content": msg}, ensure_ascii=False)
          print(f"body={payload}")
          ' >> "$GITHUB_OUTPUT"

      - name: ส่งเข้า Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.pok }}
        run: |
          curl -sS -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '${{ steps.json_payload.outputs.body }}'
